language: python
dist: xenial
matrix:
  include:
    - python: 3.6
    - python: 3.7

services: xvfb
cache: pip

addons:
  apt:
    packages:
    - gfortran
    - libncurses5-dev

install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes True --set changeps1 False
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy pandas xarray requests beautifulsoup4 lxml netCDF4 h5py nose
  - conda activate test-environment
  - conda install pytest-cov
  - conda install pytest-ordering
  - conda install coveralls
  - conda install future
  - pip install madrigalWeb
  - pip install PyForecastTools
  - pip install pysatCDF >/dev/null
  # set up data directory
  - mkdir /home/travis/build/pysatData
  # install pysat
  - python setup.py install

# command to run tests
script:
 - pytest -vs --cov=pysat/

after_success:
 - coveralls
