language: python
dist: xenial
matrix:
  include:
    - python: 3.6
    - python: 3.7

services: xvfb
cache: pip

addons:
  apt:
    packages:
    - gfortran
    - libncurses5-dev

before_install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy
  - conda install coveralls
  - conda install future
  # Travis CI currently not working with netCDF4 1.5.3
  - conda install netCDF4
  - pip install pysatCDF >/dev/null

# command to install dependencies
install:
  - conda activate test-environment
  # set up data directory
  - mkdir /home/travis/build/pysatData
  # install pysat
  - python setup.py install

# command to run tests
script:
 - nosetests -vs --with-coverage --cover-package=pysat

after_success:
 - coveralls
