language: python
dist: xenial
matrix:
  include:
    - python: 3.6
    - python: 3.7

services: xvfb
cache: pip

addons:
  apt:
    packages:
    - gfortran
    - libncurses5-dev

before_install:
  - pip install coveralls
  - pip install future
  # Travis CI currently not working with netCDF4 1.5.3
  - pip install 'cftime==1.1.1'
  - pip install 'netCDF4<1.5.3'
  - cd ..
  - git clone https://github.com/pysat/pysatCDF.git >/dev/null
  - cd ./pysatCDF
  # install pysatCDF develop
  - git checkout develop
  - python setup.py install >/dev/null
  - cd ../pysat


# command to install dependencies
install:
  - source activate test-environment
  # set up data directory
  - mkdir /home/travis/build/pysatData
  # install pysat
  - python setup.py install

# command to run tests
script:
 - nosetests -vs --with-coverage --cover-package=pysat

after_success:
 - coveralls
