language: python
dist: xenial
matrix:
  include:
    - python: 3.6
    - python: 3.7

services: xvfb
cache: pip

addons:
  apt:
    packages:
    - gfortran
    - libncurses5-dev

before_install:
  - pip install pytest-cov
  - pip install pytest-ordering
  - pip install coveralls
  - pip install future
  - pip install pysatCDF >/dev/null
  # Travis CI currently not working with netCDF4 1.5.3
  - pip install 'cftime==1.1.1'
  - pip install 'netCDF4<1.5.3'

# command to install dependencies
install:
  - source activate test-environment
  # set up data directory
  - mkdir /home/travis/build/pysatData
  # install pysat
  - python setup.py install

# command to run tests
script:
 - pytest -vs --cov=pysat/

after_success:
 - coveralls
